language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - extra-android-m2repository
    - extra-google-m2repository

sudo: required

before_install:
    - rvm install 2.4.0

script:
    - ./gradlew clean assembleDebug -PdisablePreDex --console=plain

after_script:
  - bundle install --path $HOME/vendor/bundle/
  - bundle exec danger

cache:
  directories:
    - $HOME/.gradle/wrapper/
    - $HOME/.rvm/
    - $HOME/vendor/bundle/